"""
Using TensorFlow backend.
Traceback (most recent call last):
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/Task9TrainingMNIST.py", line 1, in <module>
    from keras.datasets import mnist
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/venvcv/lib/python3.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/venvcv/lib/python3.7/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/venvcv/lib/python3.7/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/venvcv/lib/python3.7/site-packages/keras/backend/__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/venvcv/lib/python3.7/site-packages/keras/backend/load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/venvcv/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/venvcv/lib/python3.7/site-packages/tensorflow/__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/venvcv/lib/python3.7/site-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 959, in _find_and_load_unlocked
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/venvcv/lib/python3.7/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/venvcv/lib/python3.7/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/venvcv/lib/python3.7/site-packages/tensorflow_core/python/__init__.py", line 64, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/venvcv/lib/python3.7/site-packages/tensorflow_core/core/framework/graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/venvcv/lib/python3.7/site-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/venvcv/lib/python3.7/site-packages/setuptools-40.8.0-py3.7.egg/pkg_resources/__init__.py", line 84, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/venvcv/lib/python3.7/site-packages/setuptools-40.8.0-py3.7.egg/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/venvcv/lib/python3.7/site-packages/setuptools-40.8.0-py3.7.egg/pkg_resources/extern/__init__.py", line 43, in load_module
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/venvcv/lib/python3.7/site-packages/setuptools-40.8.0-py3.7.egg/pkg_resources/_vendor/pyparsing.py", line 4756, in <module>
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/venvcv/lib/python3.7/site-packages/setuptools-40.8.0-py3.7.egg/pkg_resources/_vendor/pyparsing.py", line 1284, in setParseAction
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/venvcv/lib/python3.7/site-packages/setuptools-40.8.0-py3.7.egg/pkg_resources/_vendor/pyparsing.py", line 1066, in _trim_arity
  File "/Users/teyvelina/PycharmProjects/opencv-mnist/venvcv/lib/python3.7/site-packages/setuptools-40.8.0-py3.7.egg/pkg_resources/_vendor/pyparsing.py", line 1050, in extract_stack
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 211, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 363, in extract
    f.line
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 285, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py", line 48, in getlines
    for mod in sys.modules.values():
RuntimeError: dictionary changed size during iteration
"""

https://github.com/tensorflow/tensorflow/issues/33183#issuecomment-547860088


"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py",

cd /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/
sudo su
chmod a+w linecache.py
nano linecache.py
Change
            v = sys.modules.values()
            for mod in v:
#            for mod in sys.modules.values(): (line 48)